# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emile',
            new_name='email',
        ),
    ]
